name: Build SukiSU Manager

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
      - 'userspace/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
      - 'userspace/**'
      - 'Cargo.toml'
      - 'Cargo.lock'


jobs:

  build-manager:

    name: Build Manager APK

    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: manager


    steps:

      # 拉取源码
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0


      # Java 21
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21


      # Gradle缓存
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6


      # Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4


      # 编译 Manager
      - name: Build Manager Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease


      # 上传APK
      - name: Upload Manager APK
        uses: actions/upload-artifact@v7
        with:

          name: SukiSU-Manager-release

          path: |
            manager/app/build/outputs/apk/release/*.apk

          if-no-files-found: error
